version: '3.4'

services:
  dailytodolistapi:
    image: ${DOCKER_REGISTRY-}dailytodolistapi
    build:
      context: API/src
      dockerfile: Dockerfile 
    environment:
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"  
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"

  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:4200"


