version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}dailytodolistapi
    build:
      context: ../API/src
      dockerfile: Dockerfile 
    environment:
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"  
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "44380:44380"
      - "44381:44381"

  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: ../ClientWebApp
      dockerfile: Dockerfile
    ports:
        - '4200:4200'


