name: CI

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientApp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12  

      - name: Install Dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm run test:ci

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.TOKEN_GITHUB_ACTION }}
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}

      - name: Deploy
        run: |
          npm run deploy
