name: CI

on:
  push:
    branches:
      - master
      
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npi ci
      - run: npm test
      - run: npm run deploy:web
