name: CI

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup, run tests and deploy angular app to GitHub Pages
        working-directory: ./ClientApp
      - uses: actions/setup-node@v1
        with:
          node-version: 12  
      - run: npm ci
      - run: npm test
      - run: npm run deploy:web
